### PR TITLE
the jgraph library has no mvn repo

### PR DESCRIPTION
**Pull request by phreed**
This installs into the local repo when "mvn clean" is run.
The maven build steps are now...
```
mvn clean
mvm package
```

### CODE REVIEW

**Comment by phreed** [comment]
I am not finding a description of the changes from jgraph-5.12.3.2 to jgraph-5.13.0.0
It appears that the developers have frozen jgraph at version 5.13 and recommend any new work to use jgraphx https://jgraph.github.io/mxgraph/docs/manual_javavis.html#2

**Comment by wisnesky** [comment]
There’s this: http://upstream.rosalinux.ru/java/changelogs/jgraph/5.13.0.4/changelog.html <http://upstream.rosalinux.ru/java/changelogs/jgraph/5.13.0.4/changelog.html>


It’s tempting to upgrade EASIK to use jgraphx, but its codebase is like ten years old and the original developers are all gone… its not on CI's critical path anyway

**Comment by wisnesky** [comment]
Also, the EASIK jar itself contains the source code for a particular version of jgraph… we could use that instead of using an external jar for jgraph.

http://www.mta.ca/~rrosebru/project/Easik/

**Comment by phreed** [comment]
Nothing jumps out at me from the change log explaining why 5.13 would have a problem.
Would it be safe to say that most of the FQL application uses JUNG? and not JGRAPH?
It that is the case then the fix in this patch should be sufficient.

**Comment by wisnesky** [comment]
Jgraph is only used by EASIK, everything else is JUNG.

**Comment by phreed** [comment]
I found the sources 
https://www.jgraph.com/downloads/jgraph/archive/
..and here is the comparison...
https://github.com/phreed/legacy-jgraph5/compare/v5.12.3.2...v5.13.0.0

**Comment by wisnesky** [comment]
It looks like they changed everything… I don’t see any way to figure out what part of what they did is relevant.  I have no qualms about tying AQL to specific libraries packaged in /lib, so I consider the matter closed if you do.

**Comment by phreed** [comment]
This is a patch to support the maven build.
It makes a provision to add the library to the local maven repository.
```
mvn clean
```

**Pull request merged**
