### PR TITLE
Getting Maven Build to work

### PR DESCRIPTION
**Pull request by phreed**
DO NOT ACCEPT AS IS!

This does build but I had to comment out a portion of the AqlParser.java.
      Parser<ColimSchExp<?, ?, ?, ?, ?, ?, ?>> retX = Parsers.or(ret, ret2, ret3
		// , colimExpModify(), colimSchExpQuotient(), parens(colim_ref)
                );

$ mvn package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Categorical Data IDE 0.9-SNAPSHOT-maven
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ fql ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory .../fql/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ fql ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 637 source files to .../fql/target/classes
[INFO] .../fql/src/catdata/opl/OplParser.java: Some input files use or override a deprecated API.
[INFO] .../fql/src/catdata/opl/OplParser.java: Recompile with -Xlint:deprecation for details.
[INFO] .../fql/src/easik/database/api/jdbc/JDBCDriver.java: Some input files use unchecked or unsafe operations.
[INFO] .../fql/src/easik/database/api/jdbc/JDBCDriver.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ fql ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory .../fql/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ fql ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ fql ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ fql ---
[INFO] Building jar: .../fql/target/fql-0.9-SNAPSHOT-maven.jar
[INFO] 
[INFO] --- onejar-maven-plugin:1.4.4:one-jar (default) @ fql ---
[INFO] Using One-Jar to create a single-file distribution
[INFO] Implementation Version: 0.9-SNAPSHOT-maven
[INFO] Using One-Jar version: 0.97
[INFO] More info on One-Jar: http://one-jar.sourceforge.net/
[INFO] License for One-Jar:  http://one-jar.sourceforge.net/one-jar-license.txt
[INFO] One-Jar file: .../fql/target/fql-0.9-SNAPSHOT-maven.one-jar.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.093 s
[INFO] Finished at: 2017-08-02T14:10:10-05:00
[INFO] Final Memory: 45M/1326M
[INFO] ------------------------------------------------------------------------

### CODE REVIEW

**Comment by phreed** [comment]
$ java -Xms512m -Xmx2048m -jar target/fql-0.9-SNAPSHOT-maven.one-jar.jar 
Exception in thread "main" java.lang.IllegalAccessException: Class com.simontuffs.onejar.Boot can not access a member of class catdata.ide.IDE with modifiers "public static transient"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Method.invoke(Method.java:491)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)

**Comment by wisnesky** [comment]
Can you elaborate on this error?  I don’t know what  com.simontuffs.onejar.Boot is, why it is being invoked, or why public static transient fields are incompatible with it.

**Comment by wisnesky** [comment]
I think the problem in AQLParser is due to minor type inference issues, I'll commit a version that may be more likely to succeed outside of eclipse.

**Comment by phreed** [comment]
The change to AQLParser fixed the problem. Thanks.

**Comment by phreed** [comment]
The runtime problem is apparently due to the way onejar-maven-plugin is building the comprehensive jar.
$ java -jar ./target/fql-0.9-SNAPSHOT-maven.one-jar.jar 
Exception in thread "main" java.lang.IllegalAccessException: Class com.simontuffs.onejar.Boot can not access a member of class catdata.ide.IDE with modifiers "public static transient"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Method.invoke(Method.java:491)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)

**Comment by phreed** [comment]
The problem with running the one-jar is related to the lack of  `public class IDE {`  in /fql/src/catdata/ide/IDE.java

**Comment by phreed** [comment]
Now it cannot find the examples.

$ java -jar ./target/fql-0.9-SNAPSHOT-maven.one-jar.jar 
java.lang.RuntimeException: Cannot locate built-in examples
	at catdata.ide.Examples.getAllExamples2(Examples.java:85)
	at catdata.ide.Examples.getExamples(Examples.java:179)
	at catdata.ide.Language.getExamples(Language.java:122)
	at catdata.ide.Examples.getAllExamples(Examples.java:169)
	at catdata.ide.Examples.filterBy(Examples.java:184)
	at catdata.ide.GUI.makeToolBar(GUI.java:467)
	at catdata.ide.GUI.makeGUI(GUI.java:148)
	at catdata.ide.IDE.lambda$main$0(IDE.java:67)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.util.LinkedList.addAll(LinkedList.java:408)
	at java.util.LinkedList.addAll(LinkedList.java:387)
	at catdata.ide.Examples.getAllExamples(Examples.java:169)
	at catdata.ide.Examples.filterBy(Examples.java:184)
	at catdata.ide.GUI.makeToolBar(GUI.java:467)
	at catdata.ide.GUI.makeGUI(GUI.java:148)
	at catdata.ide.IDE.lambda$main$0(IDE.java:67)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by phreed** [comment]
I will make a new pull request.

**Comment by wisnesky** [comment]
Ok, I changed the IDE class to be public (I’m not really sure why it wasn’t public to begin with.)

**Comment by wisnesky** [comment]
I’m not sure how to set up the Maven build so that the examples (resources/examples in github) folder is placed in the jar file in such a way that AQL can access them.  But I did change the loading process so that rather than halt, AQL uses no examples when the examples can’t be found.

**Pull request merged**
